# nacos 用户名密码配置
nacos:
  discovery:
    server-addr: 10.10.10.10:8848
    namespace: dev
    username: nacos
    password: nacos
    context-path: /nacos
    # contextPath也支持如下配置二选一,默认值 /nacos
    #contextPath: /nacos
    naming:
      service-name: budwk.platform
      meta-data: "{'version':'budwk.platform.8.0.0'}"
  config:
    server-addr: 10.10.10.10:8848
    namespace: dev #千万别写 public 因为查询条件是命名空间ID,而nacos默认的public命名空间ID是空白!!!
    data-id: wk-platform
    data-type: yaml
    username: nacos
    password: nacos
    context-path: /nacos
    # contextPath也支持如下配置二选一,默认值 /nacos
    #contextPath: /nacos
dubbo:
  registry:
    address: nacos://10.10.10.10:8848?namespace=dev&username=nacos&password=nacos&contextPath=/nacos
  protocol:
    name: dubbo
    threads: 200
    #随机端口
    port: 0
    #默认关闭QOS服务
  application:
    qos:
      enable: false