nutz:
  application:
    name: wk-platform
server:
  port: 0
  host: 0.0.0.0
jetty:
  contextPath: /platform
  threadpool:
    idleTimeout: 60000
    minThreads: 10
    maxThreads: 200
openapi:
  enable: true
  scanner:
    package: com.budwk.app
  info:
    title: 控制中心
    version: 8.0.0
    contact:
      name: 大鲨鱼
      email: wizzer@qq.com
  servers:
    - url: ".."
      description: 本机环境
  headers:
    - value: wk-user-token
      name: 用户Token
      in: header
      required: true
web:
  sql:
    ignore:
  cors:
    # 正式环境请改成部署的域名或网址,增加安全性
    origin: "*"
  validation:
    enable: true

redisson:
  # 集群/分片/主从等配置见 https://github.com/nutzam/nutzmore/tree/master/nutz-integration-redisson
  mode: single
  single:
    address: redis://127.0.0.1:6379
    #password: 123

redis:
  host: 127.0.0.1
  port: 6379
  timeout: 2000
  max_redir: 10
  database: 0
  maxTotal: 100
  #password: 123
  pool:
    maxTotal: 100
    maxIdle: 50
    minIdle: 10
  # cluster 集群模式
  mode: normal
  # cluster 集群模式
  #nodes:
nacos:
  discovery:
    server-addr: 10.10.10.10:8848
    namespace: dev
    naming:
      service-name: budwk.platform
      meta-data: "{'version':'budwk.platform.8.0.0'}"
  config:
    server-addr: 10.10.10.10:8848
    namespace: dev #千万别写 public 因为查询条件是命名空间ID,而nacos默认的public命名空间ID是空白!!!
    data-id: wk-platform
    data-type: yaml
dubbo:
  registry:
    address: nacos://10.10.10.10:8848?namespace=dev
  protocol:
    name: dubbo
    threads: 200
    #随机端口
    port: 0
    #默认关闭QOS服务
  application:
    qos:
      enable: false
log:
  # database=存数据库,mongodb=mongodb 此配置项只需要在 wk-platform 配置即可
  save: database
  color: true
  level: debug
database:
  enable: true
  ig:
    snowflake: true  #是否启用雪花主键
  table:
    create: true      #是否自动建表 默认false
    migration: true   #是否自动变更 默认false
    add: true         #变更是否添加列 默认false
    package:          #相关实体所在包
      - com.budwk.app
jdbc:
  url: jdbc:mysql://127.0.0.1:3306/budwk_v8?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: root
  validationQuery: select 1
  maxActive: 10
  testWhileIdle: true
  connectionProperties: druid.stat.slowSqlMillis=2000
  defaultAutoCommit: true

quartz:
  startupDelay: 10                  #延迟启动秒数
  scheduler:
    instanceName: defaultScheduler  #集群名称
    instanceId: AUTO
    skipUpdateCheck: true
  jobStore:
    class: org.quartz.impl.jdbcjobstore.JobStoreTX
    driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
    #不同数据库到适配
    #driverDelegateClass = org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
    #driverDelegateClass = org.quartz.impl.jdbcjobstore.oracle.OracleDelegate
    dataSource: myDS                #数据源名称
    tablePrefix: SYS_QRTZ_          #表前缀
    isClustered: true               #启用集群模式
    clusterCheckinInterval: 20000
    maxMisfiresToHandleAtATime: 120
    misfireThreshold: 120000
    txIsolationLevelSerializable: false
  threadPool:
    class: org.quartz.simpl.SimpleThreadPool
    threadCount: 2
    threadPriority: 5
    threadsInheritContextClassLoaderOfInitializingThread: true
  plugin:
    triggHistory:
      class: org.quartz.plugins.history.LoggingJobHistoryPlugin
    shutdownhook:
      class: org.quartz.plugins.management.ShutdownHookPlugin
      cleanShutdown: true
  dataSource:
    myDS:
      connectionProvider:
        #数据源
        class: com.budwk.app.sys.commons.task.NutConnectionProvider

storage:
  enable: true
  #本地方式
  provider: local
  local:
    #本地存储位置
    path: ~/temp/files

monitor:
  nacos:
    url: http://10.10.10.10:8848/nacos
    username: nacos
    password: nacos
    namespace: dev

job:
  # 定时任务所在的包名 多个包名用,分割
  package: com.budwk.app.sys.commons.task