export const API_WX_CONF_MINA_GET = '/platform/wx/conf/mina/get/'
export const API_WX_CONF_MINA_DELETE = '/platform/wx/conf/mina/delete/'
export const API_WX_CONF_MINA_CREATE = '/platform/wx/conf/mina/create'
export const API_WX_CONF_MINA_UPDATE = '/platform/wx/conf/mina/update'
export const API_WX_CONF_MINA_LIST = '/platform/wx/conf/mina/list'
export const API_WX_CONFIG_PAY_QUERY = '/platform/wx/conf/pay/query'
