nutz:
  application:
    name: wk-gateway
server:
  port: 9900
  host: 0.0.0.0
jetty:
  # extports: 9990 配置多端口监听,逗号分隔
  threadpool:
    idleTimeout: 60000
    minThreads: 10
    maxThreads: 2000

gateway:
  http:
    maxThreads:
    maxConnections: 256
    idleTimeout: 60000
    timeout: 100000
    requestBufferSize:
    responseBufferSize:
    # whiteList 以英文,分割
    whiteList:
    # blackList 以英文,分割
    blackList:
  route:
    load-nacos: true #是否从配置中心同步路由规则
  # 前缀转发路由
  budwk:
    filter: nacos-prefix #前缀转发路由模式
    serviceNamePrefix: budwk. #前缀名称 如请求 /platform/** 则会转发至 budwk.platform 服务
    priority: 99 #过滤器优先级
  websocket:
    group: DEFAULT_GROUP #nacos服务组,默认 DEFAULT_GROUP
    serviceName: budwk.platform #提供websocket服务的服务名
    url: /platform/websocket #转发路径

nacos:
  discovery:
    server-addr: 127.0.0.1:8848
    namespace: dev
    naming:
      service-name: gateway
      meta-data: "{'version':'budwk.gateway.8.0.0'}"
  config:
    server-addr: 127.0.0.1:8848
    namespace: dev #千万别写 public 因为查询条件是命名空间ID,而nacos默认的public命名空间ID是空白!!!
    data-id: wk-gateway
    data-type: yaml
log:
  color: true
  level: debug