package com.budwk.nb.sys.commons.core;

import com.budwk.nb.commons.constants.PlatformConstant;
import com.budwk.nb.sys.models.*;
import org.nutz.boot.NbApp;
import org.nutz.dao.Chain;
import org.nutz.dao.Dao;
import org.nutz.dao.Sqls;
import org.nutz.dao.impl.FileSqlManager;
import org.nutz.dao.sql.Sql;
import org.nutz.dao.util.Daos;
import org.nutz.ioc.loader.annotation.Inject;
import org.nutz.ioc.loader.annotation.IocBean;
import org.nutz.lang.Mirror;
import org.nutz.log.Log;
import org.nutz.log.Logs;
import org.nutz.mvc.annotation.Modules;

import java.sql.Driver;
import java.sql.DriverManager;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;

/**
 * @author wizzer(wizzer@qq.com) on 2018/3/16.
 */
@IocBean(create = "init", depose = "depose")
@Modules(packages = "com.budwk.nb")
public class SysMainLauncher {
    private static final Log log = Logs.get();

    @Inject
    private Dao dao;

    public static void main(String[] args) throws Exception {
        NbApp nb = new NbApp().setArgs(args).setPrintProcDoc(true);
        nb.getAppContext().setMainPackage("com.budwk.nb");
        nb.run();
    }

    public void init() {
        // 通过POJO类创建表结构
        try {
            Daos.createTablesInPackage(dao, "com.budwk.nb.app.sys", false);
        } catch (Exception e) {
            log.error(e);
        }

        // 若必要的数据表不存在，则初始化数据库
        if (0 == dao.count(Sys_user.class)) {
            //初始化多语言表
            Sys_lang_local langLocal=new Sys_lang_local();
            langLocal.setName("中文");
            langLocal.setLocale("zh-CN");
            langLocal.setDisabled(false);
            dao.insert(langLocal);
            langLocal=new Sys_lang_local();
            langLocal.setName("英文");
            langLocal.setLocale("en-US");
            langLocal.setDisabled(false);
            dao.insert(langLocal);
            //初始化配置表
            Sys_config conf = new Sys_config();
            conf.setConfigKey("AppName");
            conf.setConfigValue("NutzWk-V6");
            conf.setNote("系统名称");
            dao.insert(conf);
            conf = new Sys_config();
            conf.setConfigKey("AppShrotName");
            conf.setConfigValue("NutzWk");
            conf.setNote("系统短名称");
            dao.insert(conf);
            conf = new Sys_config();
            conf.setConfigKey("AppDomain");
            conf.setConfigValue("http://127.0.0.1:8080");
            conf.setNote("系统域名");
            dao.insert(conf);
            conf = new Sys_config();
            conf.setConfigKey("AppFileDomain");
            conf.setConfigValue("");
            conf.setNote("文件访问域名");
            dao.insert(conf);
            conf = new Sys_config();
            conf.setConfigKey("AppUploadBase");
            conf.setConfigValue("/upload");
            conf.setNote("文件访问路径");
            dao.insert(conf);
            conf = new Sys_config();
            conf.setConfigKey("AppWebUserOnlyOne");
            conf.setConfigValue("true");
            conf.setNote("用户单一登陆");
            dao.insert(conf);
            conf = new Sys_config();
            conf.setConfigKey("AppWebBrowserNotice");
            conf.setConfigValue("false");
            conf.setNote("启用浏览器通知");
            dao.insert(conf);
            //初始化单位
            Sys_unit unit = new Sys_unit();
            unit.setPath("0001");
            unit.setName("系统管理");
            unit.setAliasName("System");
            unit.setLocation(0);
            unit.setAddress("银河-太阳系-地球");
            unit.setEmail("wizzer@qq.com");
            unit.setTelephone("");
            unit.setHasChildren(false);
            unit.setParentId("");
            unit.setWebsite("https://wizzer.cn");
            Sys_unit dbunit = dao.insert(unit);
            //初始化菜单
            List<Sys_menu> menuList = new ArrayList<Sys_menu>();
            Sys_menu menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001");
            menu.setName("系统");
            menu.setNote("系统");
            menu.setAlias("sys");
            menu.setIcon("fa fa-cogs");
            menu.setLocation(0);
            menu.setHref("");
            menu.setTarget("");
            menu.setShowit(true);
            menu.setHasChildren(true);
            menu.setParentId("");
            menu.setType("menu");
            menu.setPermission("sys");
            Sys_menu m0 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("00010001");
            menu.setName("系统管理");
            menu.setNote("系统管理");
            menu.setAlias("sys.manage");
            menu.setIcon("fa fa-sitemap");
            menu.setLocation(1);
            menu.setHref("");
            menu.setTarget("");
            menu.setShowit(true);
            menu.setHasChildren(true);
            menu.setParentId(m0.getId());
            menu.setType("menu");
            menu.setPermission("sys.manage");
            Sys_menu m1 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("000100010001");
            menu.setName("单位管理");
            menu.setAlias("sys.manage.unit");
            menu.setLocation(0);
            menu.setHref("/platform/sys/unit");
            menu.setTarget("data-pjax");
            menu.setShowit(true);
            menu.setPermission("sys.manage.unit");
            menu.setParentId(m1.getId());
            menu.setType("menu");
            Sys_menu m2 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100010001");
            menu.setName("添加单位");
            menu.setAlias("sys.manage.unit.add");
            menu.setLocation(0);
            menu.setShowit(false);
            menu.setPermission("sys.manage.unit.add");
            menu.setParentId(m2.getId());
            menu.setType("data");
            Sys_menu m21 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100010002");
            menu.setName("修改单位");
            menu.setAlias("sys.manage.unit.edit");
            menu.setLocation(0);
            menu.setShowit(false);
            menu.setPermission("sys.manage.unit.edit");
            menu.setParentId(m2.getId());
            menu.setType("data");
            Sys_menu m22 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100010003");
            menu.setName("删除单位");
            menu.setAlias("sys.manage.unit.delete");
            menu.setLocation(0);
            menu.setShowit(false);
            menu.setPermission("sys.manage.unit.delete");
            menu.setParentId(m2.getId());
            menu.setType("data");
            Sys_menu m23 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("000100010002");
            menu.setName("用户管理");
            menu.setAlias("sys.manage.user");
            menu.setLocation(0);
            menu.setHref("/platform/sys/user");
            menu.setTarget("data-pjax");
            menu.setShowit(true);
            menu.setPermission("sys.manage.user");
            menu.setHasChildren(false);
            menu.setParentId(m1.getId());
            menu.setType("menu");
            Sys_menu m3 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100020001");
            menu.setName("添加用户");
            menu.setAlias("sys.manage.user.add");
            menu.setLocation(0);
            menu.setShowit(false);
            menu.setPermission("sys.manage.user.add");
            menu.setParentId(m3.getId());
            menu.setType("data");
            dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100020002");
            menu.setName("修改用户");
            menu.setAlias("sys.manage.user.edit");
            menu.setLocation(1);
            menu.setShowit(false);
            menu.setPermission("sys.manage.user.edit");
            menu.setParentId(m3.getId());
            menu.setType("data");
            dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100020003");
            menu.setName("删除用户");
            menu.setAlias("sys.manage.user.delete");
            menu.setLocation(2);
            menu.setShowit(false);
            menu.setPermission("sys.manage.user.delete");
            menu.setParentId(m3.getId());
            menu.setType("data");
            dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100020004");
            menu.setName("导出数据");
            menu.setAlias("sys.manage.user.export");
            menu.setLocation(3);
            menu.setShowit(false);
            menu.setPermission("sys.manage.user.export");
            menu.setParentId(m3.getId());
            menu.setType("data");
            dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("000100010003");
            menu.setName("角色管理");
            menu.setAlias("sys.manage.role");
            menu.setLocation(0);
            menu.setHref("/platform/sys/role");
            menu.setShowit(true);
            menu.setPermission("sys.manage.role");
            menu.setTarget("data-pjax");
            menu.setParentId(m1.getId());
            menu.setType("menu");
            Sys_menu m4 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100030001");
            menu.setName("添加角色");
            menu.setAlias("sys.manage.role.add");
            menu.setLocation(1);
            menu.setShowit(false);
            menu.setPermission("sys.manage.role.add");
            menu.setParentId(m4.getId());
            menu.setType("data");
            Sys_menu m41 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100030002");
            menu.setName("修改角色");
            menu.setAlias("sys.manage.role.edit");
            menu.setLocation(2);
            menu.setShowit(false);
            menu.setPermission("sys.manage.role.edit");
            menu.setParentId(m4.getId());
            menu.setType("data");
            Sys_menu m42 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100030003");
            menu.setName("删除角色");
            menu.setAlias("sys.manage.role.delete");
            menu.setLocation(3);
            menu.setShowit(false);
            menu.setPermission("sys.manage.role.delete");
            menu.setParentId(m4.getId());
            menu.setType("data");
            Sys_menu m43 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100030004");
            menu.setName("分配权限");
            menu.setAlias("sys.manage.role.menu");
            menu.setLocation(4);
            menu.setShowit(false);
            menu.setPermission("sys.manage.role.menu");
            menu.setParentId(m4.getId());
            menu.setType("data");
            Sys_menu m44 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100030005");
            menu.setName("分配用户");
            menu.setAlias("sys.manage.role.user");
            menu.setLocation(5);
            menu.setShowit(false);
            menu.setPermission("sys.manage.role.user");
            menu.setParentId(m4.getId());
            menu.setType("data");
            Sys_menu m45 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("000100010004");
            menu.setName("菜单管理");
            menu.setAlias("sys.manage.menu");
            menu.setLocation(0);
            menu.setHref("/platform/sys/menu");
            menu.setTarget("data-pjax");
            menu.setShowit(true);
            menu.setPermission("sys.manage.menu");
            menu.setParentId(m1.getId());
            menu.setType("menu");
            Sys_menu m5 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100040001");
            menu.setName("添加菜单");
            menu.setAlias("sys.manage.menu.add");
            menu.setLocation(1);
            menu.setShowit(false);
            menu.setPermission("sys.manage.menu.add");
            menu.setParentId(m5.getId());
            menu.setType("data");
            Sys_menu m51 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100040002");
            menu.setName("修改菜单");
            menu.setAlias("sys.manage.menu.edit");
            menu.setLocation(2);
            menu.setShowit(false);
            menu.setPermission("sys.manage.menu.edit");
            menu.setParentId(m5.getId());
            menu.setType("data");
            Sys_menu m52 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100040003");
            menu.setName("删除菜单");
            menu.setAlias("sys.manage.menu.delete");
            menu.setLocation(3);
            menu.setShowit(false);
            menu.setPermission("sys.manage.menu.delete");
            menu.setParentId(m5.getId());
            menu.setType("data");
            Sys_menu m53 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("000100010005");
            menu.setName("系统参数");
            menu.setAlias("sys.manage.param");
            menu.setLocation(0);
            menu.setHref("/platform/sys/param");
            menu.setTarget("data-pjax");
            menu.setShowit(true);
            menu.setPermission("sys.manage.param");
            menu.setParentId(m1.getId());
            menu.setType("menu");
            Sys_menu m6 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100050001");
            menu.setName("添加参数");
            menu.setAlias("sys.manage.param.add");
            menu.setLocation(1);
            menu.setShowit(false);
            menu.setPermission("sys.manage.param.add");
            menu.setParentId(m6.getId());
            menu.setType("data");
            Sys_menu m61 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100050002");
            menu.setName("修改参数");
            menu.setAlias("sys.manage.param.edit");
            menu.setLocation(2);
            menu.setShowit(false);
            menu.setPermission("sys.manage.param.edit");
            menu.setParentId(m6.getId());
            menu.setType("data");
            Sys_menu m62 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100050003");
            menu.setName("删除参数");
            menu.setAlias("sys.manage.param.delete");
            menu.setLocation(3);
            menu.setShowit(false);
            menu.setPermission("sys.manage.param.delete");
            menu.setParentId(m6.getId());
            menu.setType("data");
            Sys_menu m63 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("000100010006");
            menu.setName("日志管理");
            menu.setAlias("sys.manage.log");
            menu.setLocation(0);
            menu.setHref("/platform/sys/log");
            menu.setTarget("data-pjax");
            menu.setShowit(true);
            menu.setPermission("sys.manage.log");
            menu.setParentId(m1.getId());
            menu.setType("menu");
            Sys_menu m7 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100060001");
            menu.setName("删除日志");
            menu.setAlias("sys.manage.log.delete");
            menu.setLocation(1);
            menu.setShowit(false);
            menu.setPermission("sys.manage.log.delete");
            menu.setParentId(m7.getId());
            menu.setType("data");
            Sys_menu m71 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("000100010007");
            menu.setName("定时任务");
            menu.setAlias("sys.manage.task");
            menu.setLocation(0);
            menu.setHref("/platform/sys/task");
            menu.setTarget("data-pjax");
            menu.setShowit(true);
            menu.setPermission("sys.manage.task");
            menu.setParentId(m1.getId());
            menu.setType("menu");
            Sys_menu m8 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100070001");
            menu.setName("添加任务");
            menu.setAlias("sys.manage.task.add");
            menu.setLocation(1);
            menu.setShowit(false);
            menu.setPermission("sys.manage.task.add");
            menu.setParentId(m8.getId());
            menu.setType("data");
            Sys_menu m81 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100070002");
            menu.setName("修改任务");
            menu.setAlias("sys.manage.task.edit");
            menu.setLocation(2);
            menu.setShowit(false);
            menu.setPermission("sys.manage.task.edit");
            menu.setParentId(m8.getId());
            menu.setType("data");
            Sys_menu m82 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100070003");
            menu.setName("删除任务");
            menu.setAlias("sys.manage.task.delete");
            menu.setLocation(3);
            menu.setShowit(false);
            menu.setPermission("sys.manage.task.delete");
            menu.setParentId(m8.getId());
            menu.setType("data");
            Sys_menu m83 = dao.insert(menu);

            menu = new Sys_menu();
            menu.setParentId(m0.getId());
            menu.setDisabled(false);
            menu.setPath("00010002");
            menu.setName("系统配置");
            menu.setAlias("sys.config");
            menu.setType("menu");
            menu.setLocation(2);
            menu.setIcon("fa fa-cog");
            menu.setShowit(true);
            menu.setPermission("sys.config");
            menu.setHasChildren(true);
            Sys_menu pp1 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("000100020001");
            menu.setName("数据字典");
            menu.setAlias("sys.config.dict");
            menu.setLocation(0);
            menu.setHref("/platform/sys/dict");
            menu.setTarget("data-pjax");
            menu.setShowit(true);
            menu.setPermission("sys.config.dict");
            menu.setParentId(pp1.getId());
            menu.setType("menu");
            Sys_menu d = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000200010001");
            menu.setName("添加字典");
            menu.setAlias("sys.config.dict.add");
            menu.setLocation(1);
            menu.setShowit(false);
            menu.setPermission("sys.config.dict.add");
            menu.setParentId(d.getId());
            menu.setType("data");
            Sys_menu d1 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000200010002");
            menu.setName("修改字典");
            menu.setAlias("sys.config.dict.edit");
            menu.setLocation(2);
            menu.setShowit(false);
            menu.setPermission("sys.config.dict.edit");
            menu.setParentId(d.getId());
            menu.setType("data");
            Sys_menu d2 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000200010003");
            menu.setName("删除字典");
            menu.setAlias("sys.config.dict.delete");
            menu.setLocation(3);
            menu.setShowit(false);
            menu.setPermission("sys.config.dict.delete");
            menu.setParentId(d.getId());
            menu.setType("data");
            Sys_menu d3 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("000100020002");
            menu.setName("密钥管理");
            menu.setAlias("sys.config.api");
            menu.setLocation(0);
            menu.setHref("/platform/sys/api");
            menu.setTarget("data-pjax");
            menu.setShowit(true);
            menu.setPermission("sys.config.api");
            menu.setParentId(pp1.getId());
            menu.setType("menu");
            Sys_menu appManger = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000200020001");
            menu.setName("添加密钥");
            menu.setAlias("sys.config.api.add");
            menu.setLocation(0);
            menu.setShowit(false);
            menu.setPermission("sys.config.api.add");
            menu.setParentId(appManger.getId());
            menu.setType("data");
            dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000200020002");
            menu.setName("修改密钥");
            menu.setAlias("sys.config.api.edit");
            menu.setLocation(1);
            menu.setShowit(false);
            menu.setPermission("sys.config.api.edit");
            menu.setParentId(appManger.getId());
            menu.setType("data");
            dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000200020003");
            menu.setName("删除密钥");
            menu.setAlias("sys.config.api.delete");
            menu.setLocation(2);
            menu.setShowit(false);
            menu.setPermission("sys.config.api.delete");
            menu.setParentId(appManger.getId());
            menu.setType("data");
            dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("000100020003");
            menu.setName("多语言管理");
            menu.setAlias("sys.config.lang");
            menu.setLocation(0);
            menu.setHref("/platform/sys/lang");
            menu.setTarget("data-pjax");
            menu.setShowit(true);
            menu.setPermission("sys.config.lang");
            menu.setParentId(pp1.getId());
            menu.setType("menu");
            Sys_menu langManger = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000200030001");
            menu.setName("添加字符串");
            menu.setAlias("sys.config.lang.add");
            menu.setLocation(0);
            menu.setShowit(false);
            menu.setPermission("sys.config.lang.add");
            menu.setParentId(langManger.getId());
            menu.setType("data");
            dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000200030002");
            menu.setName("修改字符串");
            menu.setAlias("sys.config.lang.edit");
            menu.setLocation(1);
            menu.setShowit(false);
            menu.setPermission("sys.config.lang.edit");
            menu.setParentId(langManger.getId());
            menu.setType("data");
            dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000200030003");
            menu.setName("删除字符串");
            menu.setAlias("sys.config.lang.delete");
            menu.setLocation(2);
            menu.setShowit(false);
            menu.setPermission("sys.config.lang.delete");
            menu.setParentId(langManger.getId());
            menu.setType("data");
            dao.insert(menu);


            //消息中心及消息管理
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("00010003");
            menu.setName("消息中心");
            menu.setNote("消息中心");
            menu.setAlias("sys.msg");
            menu.setIcon("fa fa-bell");
            menu.setLocation(0);
            menu.setHref("");
            menu.setTarget("");
            menu.setShowit(false);
            menu.setHasChildren(true);
            menu.setParentId(m0.getId());
            menu.setType("menu");
            menu.setPermission("sys.msg");
            Sys_menu msg0 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("000100030001");
            menu.setName("全部消息");
            menu.setAlias("sys.msg.all");
            menu.setLocation(0);
            menu.setHref("/platform/sys/msg/user/all");
            menu.setTarget("data-pjax");
            menu.setShowit(true);
            menu.setPermission("sys.msg.all");
            menu.setParentId(msg0.getId());
            menu.setType("menu");
            dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("000100030002");
            menu.setName("未读消息");
            menu.setAlias("sys.msg.unread");
            menu.setLocation(1);
            menu.setHref("/platform/sys/msg/user/unread");
            menu.setTarget("data-pjax");
            menu.setShowit(true);
            menu.setPermission("sys.msg.unread");
            menu.setParentId(msg0.getId());
            menu.setType("menu");
            dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("000100030003");
            menu.setName("已读消息");
            menu.setAlias("sys.msg.read");
            menu.setLocation(2);
            menu.setHref("/platform/sys/msg/user/read");
            menu.setTarget("data-pjax");
            menu.setShowit(true);
            menu.setPermission("sys.msg.read");
            menu.setParentId(msg0.getId());
            menu.setType("menu");
            dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("000100010009");
            menu.setName("消息管理");
            menu.setAlias("sys.manage.msg");
            menu.setLocation(0);
            menu.setHref("/platform/sys/msg");
            menu.setTarget("data-pjax");
            menu.setShowit(true);
            menu.setPermission("sys.manage.msg");
            menu.setParentId(m1.getId());
            menu.setType("menu");
            Sys_menu msgManger = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100090001");
            menu.setName("添加消息");
            menu.setAlias("sys.manage.msg.add");
            menu.setLocation(0);
            menu.setShowit(false);
            menu.setPermission("sys.manage.msg.add");
            menu.setParentId(msgManger.getId());
            menu.setType("data");
            dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100090002");
            menu.setName("修改消息");
            menu.setAlias("sys.manage.msg.edit");
            menu.setLocation(1);
            menu.setShowit(false);
            menu.setPermission("sys.manage.msg.edit");
            menu.setParentId(msgManger.getId());
            menu.setType("data");
            dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000100090003");
            menu.setName("删除消息");
            menu.setAlias("sys.manage.msg.delete");
            menu.setLocation(2);
            menu.setShowit(false);
            menu.setPermission("sys.manage.msg.delete");
            menu.setParentId(msgManger.getId());
            menu.setType("data");
            dao.insert(menu);

            //运维中心
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("00010004");
            menu.setName("运维中心");
            menu.setNote("运维中心");
            menu.setAlias("sys.server");
            menu.setIcon("fa fa-wrench");
            menu.setLocation(0);
            menu.setHref("");
            menu.setTarget("");
            menu.setShowit(true);
            menu.setHasChildren(true);
            menu.setParentId(m0.getId());
            menu.setType("menu");
            menu.setPermission("sys.server");
            Sys_menu op0 = dao.insert(menu);
            //应用管理
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("000100040002");
            menu.setName("应用管理");
            menu.setAlias("sys.server.app");
            menu.setLocation(0);
            menu.setHref("/platform/sys/app");
            menu.setTarget("data-pjax");
            menu.setShowit(true);
            menu.setPermission("sys.server.app");
            menu.setParentId(op0.getId());
            menu.setType("menu");
            Sys_menu op02 = dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000400020001");
            menu.setName("配置文件管理");
            menu.setAlias("sys.server.app.conf");
            menu.setLocation(1);
            menu.setShowit(false);
            menu.setPermission("sys.server.app.conf");
            menu.setParentId(op02.getId());
            menu.setType("data");
            dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000400020002");
            menu.setName("Jar包管理");
            menu.setAlias("sys.server.app.jar");
            menu.setLocation(2);
            menu.setShowit(false);
            menu.setPermission("sys.server.app.jar");
            menu.setParentId(op02.getId());
            menu.setType("data");
            dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000400020003");
            menu.setName("实例管理");
            menu.setAlias("sys.server.app.instance");
            menu.setLocation(3);
            menu.setShowit(false);
            menu.setPermission("sys.server.app.instance");
            menu.setParentId(op02.getId());
            menu.setType("data");
            dao.insert(menu);
            menu = new Sys_menu();
            menu.setDisabled(false);
            menu.setPath("0001000400020004");
            menu.setName("修改日志等级");
            menu.setAlias("sys.server.app.loglevel");
            menu.setLocation(4);
            menu.setShowit(false);
            menu.setPermission("sys.server.app.loglevel");
            menu.setParentId(op02.getId());
            menu.setType("data");
            dao.insert(menu);

            //初始化角色
            Sys_role role = new Sys_role();
            role.setName("公共角色");
            role.setCode("public");
            role.setNote("All user has role");
            role.setUnitid("");
            role.setDisabled(false);
            dao.insert(role);
            role = new Sys_role();
            role.setName("系统管理员");
            role.setCode(PlatformConstant.PLATFORM_ROLE_SYSADMIN_NAME);
            role.setNote("System Admin");
            role.setUnitid("");
            role.setMenus(menuList);
            role.setDisabled(false);
            Sys_role dbrole = dao.insert(role);
            //初始化用户
            Sys_user user = new Sys_user();
            user.setId("5f8cebd7022c409a94e90da1d840b8bb");
            user.setLoginname(PlatformConstant.PLATFORM_DEFAULT_SUPERADMIN_NAME);
            user.setUsername("超级管理员");
            user.setSalt("r5tdr01s7uglfokpsdmtu15602");
            user.setPassword("1bba9287ebc50b766bff84273d11ccefaa7a8da95d078960f05f116e9d970fb0");
            user.setLoginIp("127.0.0.1");
            user.setLoginAt(0L);
            user.setLoginCount(0);
            user.setEmail("wizzer@qq.com");
            user.setUnitid(dbunit.getId());
            Sys_user dbuser = dao.insert(user);
            //不同的插入数据方式(安全)
            dao.insert("sys_user_unit", Chain.make("userId", dbuser.getId()).add("unitId", dbunit.getId()));
            dao.insert("sys_user_role", Chain.make("userId", dbuser.getId()).add("roleId", dbrole.getId()));
            //执行SQL脚本
            FileSqlManager fm = new FileSqlManager("db/");
            List<Sql> sqlList = fm.createCombo(fm.keys());
            Sql[] sqls = sqlList.toArray(new Sql[sqlList.size()]);
            for (Sql sql : sqls) {
                dao.execute(sql);
            }
            //菜单关联到角色
            dao.execute(Sqls.create("INSERT INTO sys_role_menu(roleId,menuId) SELECT @roleId,id FROM sys_menu").setParam("roleId", dbrole.getId()));
            //消息中心放第一个位置
            dao.execute(Sqls.create("update sys_menu set location=0 where path='00010003'"));
        }
    }

    public void depose() {
        // 非mysql数据库,或多webapp共享mysql驱动的话,以下语句删掉
        try {
            Mirror.me(Class.forName("com.mysql.jdbc.AbandonedConnectionCleanupThread")).invoke(null, "shutdown");
        } catch (Throwable e) {
        }
        // 解决com.alibaba.druid.proxy.DruidDriver和com.mysql.jdbc.Driver在reload时报warning的问题
        // 多webapp共享mysql驱动的话,以下语句删掉
        Enumeration<Driver> en = DriverManager.getDrivers();
        while (en.hasMoreElements()) {
            try {
                Driver driver = en.nextElement();
                String className = driver.getClass().getName();
                log.debug("deregisterDriver: " + className);
                DriverManager.deregisterDriver(driver);
            } catch (Exception e) {
            }
        }
    }
}
