export const API_WX_CONFIG_PAY_GET = '/wechat/admin/conf/pay/get/'
export const API_WX_CONFIG_PAY_DELETE = '/wechat/admin/conf/pay/delete/'
export const API_WX_CONFIG_PAY_CREATE = '/wechat/admin/conf/pay/create'
export const API_WX_CONFIG_PAY_UPDATE = '/wechat/admin/conf/pay/update'
export const API_WX_CONFIG_PAY_LIST = '/wechat/admin/conf/pay/list'
export const API_WX_CONFIG_PAYCERT_LIST = '/wechat/admin/conf/pay/cert/list'
