export const API_WX_REPLY_IMG_GET = '/wechat/admin/reply/img/get/'
export const API_WX_REPLY_IMG_DELETE = '/wechat/admin/reply/img/delete/'
export const API_WX_REPLY_IMG_DELETE_MORE = '/wechat/admin/reply/img/delete_more'
export const API_WX_REPLY_IMG_CREATE = '/wechat/admin/reply/img/create'
export const API_WX_REPLY_IMG_UPDATE = '/wechat/admin/reply/img/update'
export const API_WX_REPLY_IMG_LIST = '/wechat/admin/reply/img/list'
