export const API_SYS_MSG_LIST = '/platform/sys/msg/list'
export const API_SYS_MSG_CREATE = '/platform/sys/msg/create'
export const API_SYS_MSG_DELETE = '/platform/sys/msg/delete/'
export const API_SYS_MSG_GET_TYPE = '/platform/sys/msg/get_type'
export const API_SYS_MSG_GET_USER_VIEW_LIST = '/platform/sys/msg/get_user_view_list'
export const API_SYS_MSG_SELECT_USER_LIST = '/platform/sys/msg/select_user_list'
export const API_SYS_MSG_DATA = '/platform/sys/msg/data'
