export const API_SYS_POST_LIST = '/platform/sys/post/list'
export const API_SYS_POST_GET = '/platform/sys/post/get/'
export const API_SYS_POST_CREATE = '/platform/sys/post/create'
export const API_SYS_POST_DELETE = '/platform/sys/post/delete/'
export const API_SYS_POST_UPDATE = '/platform/sys/post/update'
export const API_SYS_POST_LOCATION = '/platform/sys/post/location'
