nutz:
  application:
    name: wk-cms
server:
  port: 0
  host: 0.0.0.0
jetty:
  contextPath: /cms
  threadpool:
    idleTimeout: 60000
    minThreads: 10
    maxThreads: 200
openapi:
  enable: true
  scanner:
    package: com.budwk.app
  info:
    title: CMS内容管理
    version: 8.0.0
    contact:
      name: 大鲨鱼
      email: wizzer@qq.com
  servers:
    - url: ".."
      description: 本机环境
  headers:
    - value: wk-user-token
      name: 用户Token
      in: header
      required: true
web:
  sql:
    ignore:
  cors:
    # 正式环境请改成部署的域名或网址,增加安全性
    origin: "*"
  validation:
    enable: true
redis:
  host: 127.0.0.1
  port: 6379
  timeout: 2000
  max_redir: 10
  database: 0
  maxTotal: 100
  #password: 123
  pool:
    maxTotal: 100
    maxIdle: 50
    minIdle: 10
  # cluster 集群模式
  mode: normal
  # cluster 集群模式
  #nodes:
nacos:
  discovery:
    server-addr: 127.0.0.1:8848
    namespace: dev
    naming:
      service-name: budwk.cms
      meta-data: "{'version':'budwk.cms.8.0.0'}"
  config:
    server-addr: 127.0.0.1:8848
    namespace: dev #千万别写 public 因为查询条件是命名空间ID,而nacos默认的public命名空间ID是空白!!!
    data-id: wk-cms
    data-type: yaml
dubbo:
  registry:
    address: nacos://127.0.0.1:8848?namespace=dev
  protocol:
    name: dubbo
    threads: 200
    #随机端口
    port: 0
    #默认关闭QOS服务
  application:
    qos:
      enable: false
log:
  color: true
  level: debug
database:
  enable: true
  ig:
    snowflake: true  #是否启用雪花主键
  table:
    create: true      #是否自动建表 默认false
    migration: true   #是否自动变更 默认false
    add: true         #变更是否添加列 默认false
    package:          #相关实体所在包
      - com.budwk.app
jdbc:
  url: jdbc:mysql://127.0.0.1:3306/budwk_v7?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
  username: root
  password: root
  validationQuery: select 1
  maxActive: 10
  testWhileIdle: true
  connectionProperties: druid.stat.slowSqlMillis=2000
  defaultAutoCommit: true

storage:
  enable: true
  #本地方式
  provider: local
  local:
    #本地存储位置
    path: ~/temp/files

